// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
//
// import 'package:flutter/foundation.dart' show defaultTargetPlatform;
// import 'package:flutter/foundation.dart' show TargetPlatform;
// import 'package:firebase_core/firebase_core.dart';
//
// enum Environment { devDriver ,prodDriver}
//
// class Constants {
//
//
//   static late Map<String, dynamic>? _config;
//   static late String? serverKey;
//   static  String? serverKeyTesting="AAAAD7W2RUQ:APA91bEGv8oE6mHJ2IrQBI1X4Q5PjDMsPLNM7cfnjqIIiiiZR5sUtgHnCn5iWLJAcu7WNkOXi7b7Diloh-3pXEvccoZnAIueZD0nlO2lBuJ1vN2nvSQD3mtk5FF-2ehSutV6ulzpopCL";
//   static  String? serverKeyProd="AAAA73eWSDA:APA91bHSChlH2P-v-JO5WlSG3k00GueiWhG1AEVCBtZZiG-279uPa7WT6h-K2oIAU7Ej_pixTYRolB8xRDSdT4MndbsZBpHsDIury4o1YV6gtXgJMbp9Ns9KFlF0xHXTAZOZ7Pl55iWu";
//   static void setEnvironment(Environment env,) {
//     switch (env) {
//       case Environment.devDriver :
//         _config = _DefaultFirebaseOptions.debugDriver;
//         serverKey=serverKeyTesting;
//         break;
//       case Environment.prodDriver :
//         _config = _DefaultFirebaseOptions.prodDriver;
//         serverKey=serverKeyProd;
//         break;
//
//     }
//   }
//
//   static get baseUrl {
//     return _config![_DefaultFirebaseOptions.baseUrl];
//   }
//   static get gogoleMapKey {
//     return _config![_DefaultFirebaseOptions.gogoleMapKey];
//   }
//
//   static get currentPlatform {
//     if (defaultTargetPlatform == TargetPlatform.android) {
//       if (_config != null) {
//         return _config![_DefaultFirebaseOptions.filOptsAndroid];
//       }
//     } else if (defaultTargetPlatform == TargetPlatform.iOS) {
//       if (_config != null) {
//         return _config![_DefaultFirebaseOptions.filOptsIos];
//       }
//     }
//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }
// }
//
// class _DefaultFirebaseOptions {
//   static const baseUrl = "url";
//   static const gogoleMapKey = "gogoleMapKey";
//   static const filOptsIos = "firebase";
//   static const filOptsAndroid = "firebase";
//
//   static Map<String, dynamic> debugDriver = {
//     baseUrl: "https://driverapitestlinux.azurewebsites.net/api/v2/",
//     gogoleMapKey: "AIzaSyC1JdN6UIK_jSvYIvPyxiGwflL-019MwnY",
//     filOptsAndroid: const FirebaseOptions(
//       apiKey: 'AIzaSyBJTIkVcgxMSOa9wwumb6CJDKGsJBJFIvw',
//       appId: '1:880449043491:android:7af8a08a76133a68f68596',
//       messagingSenderId: '880449043491',
//       projectId: 'saboba-3c66e',
//       storageBucket: 'saboba-3c66e.appspot.com',
//     ),
//     filOptsIos: const FirebaseOptions(
//       apiKey: 'AIzaSyCdfbUpaof9CaO2OCLnKtr9Kc4bT0k1RI0',
//       appId: '1:880449043491:ios:ca93ba80bddd715af68596',
//       messagingSenderId: '880449043491',
//       projectId: 'saboba-3c66e',
//       storageBucket: 'saboba-3c66e.appspot.com',
//       // androidClientId:
//       // '67473130820-22l0qao8dva1qtamqf8tveaq795nfa91.apps.googleusercontent.com',
//       // iosClientId:
//       // '67473130820-09rq9q217c0nq9jamjr6rnv25fkrlviu.apps.googleusercontent.com',
//       iosBundleId: 'com.saboba.app',
//     )
//   };
//
//   static Map<String, dynamic> prodDriver = {
//     baseUrl: 'https://urdriverprodapilinux.azurewebsites.net/api/v2/',
//     gogoleMapKey: "AIzaSyBRGqgkf9Vfk6BSWYcFOkuQcN3P7h-Us0Q",
//
//     filOptsAndroid: const FirebaseOptions(
//       apiKey: 'AIzaSyAUjtlVM0p22ZrZkuH-hTv-pmw0XlgtfJ8',
//       appId: '1:1028503521328:android:ef5338238ce30cd45445f5',
//       messagingSenderId: '1028503521328',
//       projectId: 'upryde-14191',
//       databaseURL: 'https://upryde-14191-default-rtdb.firebaseio.com',
//       storageBucket: 'upryde-14191.appspot.com',
//     ),
//     filOptsIos: const FirebaseOptions(
//       apiKey: 'AIzaSyDrGpLUwL7Oc3y5VMNmC_lDyuxUWnfOUes',
//       appId: '1:1028503521328:ios:5ac8ee8f40e1b7de5445f5',
//       messagingSenderId: '1028503521328',
//       projectId: 'upryde-14191',
//       databaseURL: 'https://upryde-14191-default-rtdb.firebaseio.com',
//       storageBucket: 'upryde-14191.appspot.com',
//       androidClientId:
//       '1028503521328-8icn4ha6bpg0reeoofepmrsum6nbcilh.apps.googleusercontent.com',
//       iosClientId:
//       '1028503521328-6vqq76qkuf0j9soe4v5as9ee56j1f9o3.apps.googleusercontent.com',
//       iosBundleId: 'com.upryde.driver',
//     )
//   };
//
//
//
//
//
//
//
//
// }
//
//
//
