name: core
description: A new Flutter project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../dependencies



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  json_annotation:
  json_serializable:

dependency_overrides:
  intl: ^0.18.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
#
#  assets:
#    - ../lang/en.json
#    - ../lang/ar.json
##    - ../assets/
##    - ../assets/fonts/
