name: art_core
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter




  dependencies:
    path: ../dependencies
  core:
    path: ../core

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0


flutter:




  uses-material-design: true

  assets:
    - ../assets/
    - ../assets/images/
    - ../assets/images/bottom_nav_icons/
    - ../assets/fonts/


  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: ../assets/fonts/HelveticaNeueBlackRegular.otf
          weight: 400
        - asset: ../assets/fonts/HelveticaNeueMedium.otf
          weight: 500
        - asset: ../assets/fonts/HelveticaNeueBold.otf
          weight: 700





















