name: dependencies
description: A new Flutter project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  get_storage: ^2.0.2
  easy_localization: 3.0.7
  dio: 5.4.0
  internet_connection_checker: ^1.0.0+1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.0
  lottie: ^2.2.0
  intl:  0.19.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  image_picker: ^0.8.6+1
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.10
  url_launcher: ^6.2.4
  build_runner:
  freezed:
  freezed_annotation:
  json_annotation:
  json_serializable:
  pin_code_fields: ^8.0.1
  network_logger: ^1.0.4
  flutter_switch: ^0.3.2
  pull_to_refresh: ^2.0.0
  image_cropper: ^5.0.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  webview_flutter: 4.4.4
  cached_network_image: ^3.2.3
  device_info_plus: ^10.0.1
  package_info_plus: ^8.1.1
#  firebase_dynamic_links: ^5.5.0
  onesignal_flutter: ^5.0.0
  dropdown_search: ^6.0.1
  pdf: ^3.3.0

  smooth_page_indicator: ^1.1.0
  blurrycontainer: ^2.1.0
  dotted_border: ^2.1.0
  flutter_pdfview: ^1.2.1
  printing: ^5.13.2
  http: ^1.2.2
  print_bluetooth_thermal: ^1.0.5
  flutter_rating_bar: ^4.0.0
  gauge_indicator: ^0.4.3
  pie_chart: ^5.4.0
  fl_chart: 0.69.2
  syncfusion_flutter_charts: ^27.2.5
  flutter_echarts: ^2.5.0

  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1
  flutter_gen_runner: ^5.4.0


dependency_overrides:
  intl: 0.19.0
  web: ^1.0.0

flutter:





